# Generated by Django 2.1.1 on 2018-09-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20180922_0115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cv',
            new_name='Informazioni_Personali',
        ),
    ]
