# Generated by Django 2.1.1 on 2018-09-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_esperienza_lavorativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informazione_Istruzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da', models.DateField(blank=True, null=True)),
                ('data_a', models.DateField(blank=True, null=True)),
                ('nome_formazione', models.CharField(max_length=100)),
                ('materia_studio', models.CharField(max_length=100)),
                ('qualifica', models.CharField(max_length=100)),
                ('punteggio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali')),
            ],
            options={
                'verbose_name_plural': 'Qualifiche',
            },
        ),
    ]
