# Generated by Django 2.1.1 on 2018-09-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_informazione_istruzione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap_Lingue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lingua', models.CharField(max_length=100)),
                ('lettura', models.CharField(choices=[('Elementare', 'Elementare'), ('Buono', 'Buono'), ('Eccellente', 'Eccellente')], max_length=10)),
                ('scrittura', models.CharField(choices=[('Elementare', 'Elementare'), ('Buono', 'Buono'), ('Eccellente', 'Eccellente')], max_length=10)),
                ('orale', models.CharField(choices=[('Elementare', 'Elementare'), ('Buono', 'Buono'), ('Eccellente', 'Eccellente')], max_length=10)),
                ('id_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali')),
            ],
            options={
                'verbose_name_plural': 'Capacità Linguistiche',
            },
        ),
    ]
