# Generated by Django 2.1.1 on 2018-09-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_auto_20180922_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informazioni_personali',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='informazioni_personali',
            name='patenti',
        ),
    ]
