# Generated by Django 2.1.1 on 2018-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_auto_20180925_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esperienza_lavorativa',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='esperienza_lavorativa',
            name='data_da',
        ),
        migrations.RemoveField(
            model_name='informazione_istruzione',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='informazione_istruzione',
            name='data_da',
        ),
        migrations.AddField(
            model_name='esperienza_lavorativa',
            name='data_da_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informazione_istruzione',
            name='data_da_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
