# Generated by Django 2.1.1 on 2018-09-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_auto_20180925_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperienza_lavorativa',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
        migrations.AlterField(
            model_name='informazione_istruzione',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
    ]
