# Generated by Django 2.1.1 on 2018-10-07 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_auto_20180928_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='informazioni_personali',
            name='foto_tessera',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comp_artistiche',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
        migrations.AlterField(
            model_name='comp_organizzative',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
        migrations.AlterField(
            model_name='comp_relazionali',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
        migrations.AlterField(
            model_name='comp_tecniche',
            name='id_resume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali'),
        ),
    ]
