# Generated by Django 2.1.1 on 2018-10-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_auto_20181007_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informazioni_personali',
            name='foto_tessera',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
