# Generated by Django 2.1.1 on 2018-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0017_auto_20181208_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='informazioni_personali',
            name='patenti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
