# Generated by Django 2.1.1 on 2018-12-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0018_informazioni_personali_patenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Altre_Informa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altre_informazioni', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Informazioni_Personali')),
            ],
            options={
                'verbose_name_plural': 'Altre Informazioni',
            },
        ),
    ]
